# Generated by Django 5.2.5 on 2025-09-06 04:33

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('FAILED', 'FAILED'), ('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('REFUNDED', 'REFUNDED')], default=listings.models.PaymentStatus['PENDING'], max_length=10),
        ),
    ]
